/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proodos;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author User
 */
public class TreeForm extends javax.swing.JFrame {

    /**
     * Creates new form TreeForm
     */
    public TreeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("ΒΑΣΗ ΔΕΔΟΜΕΝΩΝ");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ΠΙΝΑΚΕΣ");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Στοιχεία Εργαζομένων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Πρόσθετα Στοιχεία Εργαζομένων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Τύπος Εργαζομένων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Τηλέφωνα Εργαζομένων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email Εργαζομένων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ημερομηνίες προσλήψεων/απολύσεων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Μισθοί εργαζομένων");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ισχύς μισθών");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Αποδοχές");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Άδειες/Άσθενειες");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Εξουσιοδοτημένοι χρήστες");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTree2.setDropMode(javax.swing.DropMode.ON);
        jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseClicked

    if (evt.getClickCount() == 1) { 
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree2.getSelectionPath().getLastPathComponent();

        if (selectedNode.isLeaf()&&   "Στοιχεία Εργαζομένων".equals(selectedNode.toString())) {

            Pinakas1 t = new Pinakas1();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    }//GEN-LAST:event_jTree2MouseClicked
        else if (selectedNode.isLeaf()&&   "Πρόσθετα Στοιχεία Εργαζομένων".equals(selectedNode.toString())) {

            Pinakas2 t = new Pinakas2();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Τύπος Εργαζομένων".equals(selectedNode.toString())) {

            Pinakas3 t = new Pinakas3();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Τηλέφωνα Εργαζομένων".equals(selectedNode.toString())) {

            Pinakas4 t = new Pinakas4();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Email Εργαζομένων".equals(selectedNode.toString())) {

            Pinakas5 t = new Pinakas5();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Ημερομηνίες προσλήψεων/απολύσεων".equals(selectedNode.toString())) {

            Pinakas6 t = new Pinakas6();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Μισθοί εργαζομένων".equals(selectedNode.toString())) {

            Pinakas7 t = new Pinakas7();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Ισχύς μισθών" .equals(selectedNode.toString())) {

            Pinakas8 t = new Pinakas8();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Αποδοχές".equals(selectedNode.toString())) {

            Pinakas9 t = new Pinakas9();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Άδειες/Άσθενειες".equals(selectedNode.toString())) {

            Pinakas10 t = new Pinakas10();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        else if (selectedNode.isLeaf()&&   "Εξουσιοδοτημένοι χρήστες".equals(selectedNode.toString())) {

            Pinakas11 t = new Pinakas11();
            t.setVisible(true);
            this.setVisible(false);
            this.dispose();

    } 
        
    }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables
}
